/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityCitySlugChar123ProjectSlugChar125RouteImport } from './routes/city.$citySlug.{-$projectSlug}'
import { Route as ApiPublicHooksImportOsmRouteImport } from './routes/api/public/hooks/import-osm'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCitySlugChar123ProjectSlugChar125Route =
  CityCitySlugChar123ProjectSlugChar125RouteImport.update({
    id: '/city/$citySlug/{-$projectSlug}',
    path: '/city/$citySlug/{-$projectSlug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksImportOsmRoute = ApiPublicHooksImportOsmRouteImport.update({
  id: '/api/public/hooks/import-osm',
  path: '/api/public/hooks/import-osm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/submissions': typeof SubmissionsRoute
  '/city/$citySlug/{-$projectSlug}': typeof CityCitySlugChar123ProjectSlugChar125Route
  '/api/public/hooks/import-osm': typeof ApiPublicHooksImportOsmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/submissions': typeof SubmissionsRoute
  '/city/$citySlug/{-$projectSlug}': typeof CityCitySlugChar123ProjectSlugChar125Route
  '/api/public/hooks/import-osm': typeof ApiPublicHooksImportOsmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/submissions': typeof SubmissionsRoute
  '/city/$citySlug/{-$projectSlug}': typeof CityCitySlugChar123ProjectSlugChar125Route
  '/api/public/hooks/import-osm': typeof ApiPublicHooksImportOsmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/submissions'
    | '/city/$citySlug/{-$projectSlug}'
    | '/api/public/hooks/import-osm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/submissions'
    | '/city/$citySlug/{-$projectSlug}'
    | '/api/public/hooks/import-osm'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/submissions'
    | '/city/$citySlug/{-$projectSlug}'
    | '/api/public/hooks/import-osm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  SubmissionsRoute: typeof SubmissionsRoute
  CityCitySlugChar123ProjectSlugChar125Route: typeof CityCitySlugChar123ProjectSlugChar125Route
  ApiPublicHooksImportOsmRoute: typeof ApiPublicHooksImportOsmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$citySlug/{-$projectSlug}': {
      id: '/city/$citySlug/{-$projectSlug}'
      path: '/city/$citySlug/{-$projectSlug}'
      fullPath: '/city/$citySlug/{-$projectSlug}'
      preLoaderRoute: typeof CityCitySlugChar123ProjectSlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-osm': {
      id: '/api/public/hooks/import-osm'
      path: '/api/public/hooks/import-osm'
      fullPath: '/api/public/hooks/import-osm'
      preLoaderRoute: typeof ApiPublicHooksImportOsmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  SubmissionsRoute: SubmissionsRoute,
  CityCitySlugChar123ProjectSlugChar125Route:
    CityCitySlugChar123ProjectSlugChar125Route,
  ApiPublicHooksImportOsmRoute: ApiPublicHooksImportOsmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
